### ISSUE TITLE
Accessibility page could do with an introductory sentence?

### ISSUE THREAD

**Issue by birtles** [mozdevs/Animation-examples#17]
I wasn't entirely sure what sort of accessibility requirements were in mind. One common requirement is people with [vestibular disorder](http://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity) where I think we'd actually want the animation not to run at all?

**Comment by belen-albeza** [comment]
Thanks! Added a paragraph explaining a bit this demo.
