### ISSUE TITLE
Offsets are not strictly necessary in the source code comparison

### ISSUE THREAD

**Issue by birtles** [mozdevs/Animation-examples#19]
And as a very minor point--in the first example, offsets are listed for each of the keyframes. This makes the correspondence with the CSS animations syntax clear, however, strictly speaking, the offsets are not needed since the Web Animations API will evenly space the keyframes automatically whenever offsets are missing.

That is

``` js
let el = document.querySelector('.rainbow');
el.animate([
    { background: '#ff004d', offset: 0 },
    { background: '#ff77ab', offset: 0.25 },
    { background: '#00e756', offset: 0.5 },
    { background: '#29adff', offset: 0.75 },
    { background: '#ff77ab', offset: 1 }
], {
    duration: 2000,
    direction: 'alternate',
    iterations: Infinity
});
```

could be written as:

``` js
let el = document.querySelector('.rainbow');
el.animate([
    { background: '#ff004d' },
    { background: '#ff77ab' },
    { background: '#00e756' },
    { background: '#29adff' },
    { background: '#ff77ab' }
], {
    duration: 2000,
    direction: 'alternate',
    iterations: Infinity
});
```

Or even:

``` js
let el = document.querySelector('.rainbow');
el.animate({
    background: [ '#ff004d', '#ff77ab', '#00e756', '#29adff', '#ff77ab' ]
}, {
    duration: 2000,
    direction: 'alternate',
    iterations: Infinity
});
```

I'm pretty sure you knew that but I wasn't sure if it deserves a mention or not, though.

**Comment by belen-albeza** [comment]
Hi, yes we knew. The issue here is that explicitly declaring the offsets is a more complete example (i.e. it allows you to do "more"). I'm a bit torn about this, maybe an example where the offsets are not evenly spread would be a better one…

**Comment by belen-albeza** [comment]
Made the keyframes not evenly spread :)

**Comment by birtles** [comment]
Excellent, thank you!
