### ISSUE TITLE
Write a decent README

### ISSUE THREAD

**Issue by belen-albeza** [mozdevs/Animation-examples#5]
- Explain how to access the demos online
- Explain how to run the demos locally
- Explain how to collaborate and invite people to do it

**Comment by samuknet** [comment]
@belen-albeza  @sole  Have done a 'first version' of this.  Let me know if I have missed anything and of course feel free to tweak it yourself.

**Comment by belen-albeza** [comment]
Hi @samuknet thanks! :) I added a bit more stuff in this PR https://github.com/mozdevs/Animation-examples/pull/11

**Comment by samuknet** [comment]
@belen-albeza Great, just merged it in :)
