### ISSUE TITLE
use gh-pages as default

### ISSUE THREAD

**Issue by sole** [mozdevs/Animation-examples#8]
Can we please make `gh-pages` the default branch so we can see these examples online? ease of share and etc...

If no one objects I'll do it and delete the `master` branch.

**Comment by sole** [comment]
@belen-albeza @samuknet thoughts?

**Comment by samuknet** [comment]
Sounds good to me, I have nothing against it

**Comment by belen-albeza** [comment]
Yes, I actually thought I've already done it 😊 But looks like I forgot!

**Comment by belen-albeza** [comment]
Done

**Comment by samuknet** [comment]
Could we add a link to [https://mozdevs.github.io/Animation-examples/](https://mozdevs.github.io/Animation-examples/) in the repos. description?

**Comment by sole** [comment]
@samuknet I just did that, and deleted the `master` branch 💥💀

**Comment by sole** [comment]
@samuknet also next time feel free to just do it yourself! 😃

**Comment by samuknet** [comment]
I didn't have permissions :(

**Comment by belen-albeza** [comment]
> I didn't have permissions :(

Shame on me! Now you do :)
